### ISSUE TITLE
有几个地方数据错了

### ISSUE THREAD

**Issue by orzmand** [AnnAngela/FFXIVSightseeingGuide#20]
第10个坐标是10,6，现在是10,16；
第13个天气是晴朗也可以

**Comment by orzmand** [comment]
而且现在时间没到也显示“现在就可以完成”

**Comment by AnnAngela** [comment]
好的，等我旅游回来检查一下

**Comment by AnnAngela** [comment]
> 第10个坐标是10,6，现在是10,16；
> 第13个天气是晴朗也可以

已修正（13号我直接改成晴朗了）

> 而且现在时间没到也显示“现在就可以完成”

这个我无法复现
